### ISSUE TITLE
Query not working on Windows

### ISSUE THREAD

**Issue by masalmon** [osmdatar/osmdata#23] opened 2016-12-18 19:23 UTC
I'm currently using the package in RStudio on Windows.

* When I test the package with `testthat`, everything works ok.

* I am attaching the results of R CHECK. The errors are due to examples in which there are comments about their not working so seems ok?
[osmdata_check_results.txt](https://github.com/osmdatar/osmdata/files/659597/osmdata_check_results.txt)

* If I run this query in my R session
```{r}
qry <- opq(bbox=c(-0.12,51.11,-0.11,51.12)) 
qry <- add_feature (qry, key='highway', value='tertiary')
res <- overpass_query (qry)

```
The session aborts not long after the message
```{r}
Issuing query to OSM Overpass...
Rate limit: 2
```

I re-started and now I actually get an error instead of session abortion

```{r}
> qry <- opq(bbox=c(-0.12,51.11,-0.11,51.12)) 
> qry <- add_feature (qry, key='highway', value='tertiary')
> res <- overpass_query (qry)
Issuing query to OSM Overpass...
2 slots available now.
[1] "2 slots available now."
 Show Traceback
 
 Rerun with Debug
 Error in make_query(query, quiet) : Bad Request (HTTP 400). 
```

It seems quite weird to me. I can't investigate further today, but I'll try to take a few minutes this week at work to install the package and run the same steps there (still Windows).

**Comment by masalmon** [comment] 2016-12-18 19:40
I've even re-started my computer, still getting the HTTP 400 error, even with another example from the README

```r
> q0 <- opq (bbox=osmdata::getbb ("Bonn")) # Bonn, Germany
> q1 <- add_feature (q0, key="railway", value="station")
> overpass_query (q1, quiet=TRUE)
[1] "2 slots available now."
 Show Traceback
 
 Rerun with Debug
 Error in make_query(query, quiet) : Bad Request (HTTP 400). 
```

If I print q1 it is
```

$bbox
[1] "50.575851,6.94066,50.895851,7.26066"

$features
[1] "[out:xml][timeout:25];\n(\n"                                                                                                                                                                                              
[2] " node[\"railway\"=\"station\"](50.575851,6.94066,50.895851,7.26066);\n  way[\"railway\"=\"station\"](50.575851,6.94066,50.895851,7.26066);\n  relation[\"railway\"=\"station\"](50.575851,6.94066,50.895851,7.26066);\n\n"
```

and `qry` from the other example is

```r
$bbox
[1] "51.11,-0.12,51.12,-0.11"

$features
[1] "[out:xml][timeout:25];\n(\n"                                                                                                                                                             
[2] " node[\"highway\"=\"tertiary\"](51.11,-0.12,51.12,-0.11);\n  way[\"highway\"=\"tertiary\"](51.11,-0.12,51.12,-0.11);\n  relation[\"highway\"=\"tertiary\"](51.11,-0.12,51.12,-0.11);\n\n"
```

That's all for today, sorry about that.

**Comment by mpadge** [comment] 2016-12-19 09:11
This may well be because of the stubbing out of `httr:POST` calls with [this function](https://github.com/osmdatar/osmdata/blob/master/R/stub.R). Normal usage should *not* be stubbed, but you could try inserting an `else` after [this `if` clause](https://github.com/osmdatar/osmdata/blob/master/R/overpass-query.R#L140-L141) to examine whether that may be the cause ... The stubbed content is generated by setting [`get_local=TRUE` here](https://github.com/osmdatar/osmdata/blob/master/tests/testthat/test-osmdata.R#L36), and used for example [here](https://github.com/osmdatar/osmdata/blob/master/tests/testthat/test-osmdata.R#L71-L76).

**Comment by masalmon** [comment] 2016-12-19 12:54
The examples above work on my PC at work (still Windows) :thinking: Is it due to something you've changed today @mpadge or is it pure luck?

**Comment by masalmon** [comment] 2016-12-19 12:57
Could you/I add Appveyor CI by the way? And on Travis it's possible to check Mac as well as Linus.

**Comment by mpadge** [comment] 2016-12-19 13:09
Pure luck i'd say ... i did go over the stubs today with the proverbial fine-toothed comb, but they all seemed okay, and i don't think i changed any functionality there.

**Comment by masalmon** [comment] 2016-12-19 13:39
Ok, I'll have a word with my laptop tonight :grin:

**Comment by masalmon** [comment] 2016-12-19 13:39
Or maybe I should leave this open?

**Comment by mpadge** [comment] 2016-12-19 14:48
Appveyor says [close this issue](https://ci.appveyor.com/project/mpadge/osmdata/build/1.0.4#L681) - because all tests pass, so your problem must have been resolved.

**Comment by masalmon** [comment] 2017-01-25 10:24
Re-opening this, the query of the chunk "query-thames" in the README makes my session abort. :cry:

**Comment by mpadge** [comment] 2017-01-25 10:30
I'm in the process of cleaning up lots of the `sf` code, so maybe give it another try later today. Let me know if the problem persists. It certainly works on my machine. What OS are you on? It'd be great to have constant comparison with non-linux systems ...

**Comment by masalmon** [comment] 2017-01-25 10:33
I'm both the Windows and encoding test person :wink: 

Also I had a fork but now that I can push to the repo, maybe I can add the docs/ directly once I can knit the README, it won't give any conflict after all.

**Comment by mpadge** [comment] 2017-01-25 12:47
okay Maëlle, main C++ code is much tidier now and a couple of fixes implemented. Please re-try and let me know

**Comment by masalmon** [comment] 2017-01-25 14:12
Thanks. It's so weird, the README could be knit but then `pkgdown::build_home()` failed until I deleted README.Rmd so that it wouldn't knit it again. :angel: If the problem persists I'll try to see if it's a `osmdatar` or a `pkgdown` issue.

**Closed** 2017-02-14 13:56 UTC

**Comment by masalmon** [comment] 2017-02-14 14:19
Just tried to rebuild the website, RStudio froze. I'm doing a R CHECK now.

**Comment by mpadge** [comment] 2017-02-14 14:21
That could be because the overpass API has been quite overloaded lately - appveyor builds generally crash because of timeout errors.

**Comment by masalmon** [comment] 2017-02-14 14:23
And the `overpass_status` function isn't enough to prevent this?

**Comment by mpadge** [comment] 2017-02-14 14:25
nah, it happens when status is initially okay so a query is allowed through, but then times out once issued

**Comment by masalmon** [comment] 2017-02-14 14:26
oooh isn't this a bug for Overpass? Should it be reported somewhere?
